---
# tasks file for third-party-tools-install
- name: Install wget
  yum:
    name: wget
    state: present

- name: Install Git
  yum:
    name: git
    state: present

- name: Install Net Tools
  yum:
    name: net-tools
    state: present

- name: Install Bind Utils
  yum:
    name: bind-utils
    state: present

- name: Install IPTables Services
  yum:
    name: iptables-services
    state: present

- name: Install Bridge Utils
  yum:
    name: bridge-utils
    state: present

- name: Install Bash Completion
  yum:
    name: bash-completion
    state: present

#3.7 ??
- name: Install kexec-tools
  yum:
    name: kexec-tools
    state: present

- name: Install sos 
  yum:
    name: sos
    state: present

- name: Install psacct 
  yum:
    name: psacct
    state: present
