---
# tasks file for subscription-manager-ocp
- name: Install Subscription Manager
  yum:
    name: subscription-manager
    state: present

- name: check to see if system is already registered
  command: subscription-manager status
  register: sub_status
  ignore_errors: true

- name:
  debug: msg={{rhn_user}}
- name:
  debug: msg={{rhn_pool_id}}
- name:
  debug: msg={{ocp_repos}}

- name: Register system
  redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_pass }}"
    #pool_ids: "{{ rhn_pool_id }}"
    pool: "{{ rhn_pool_id }}"
    # this force may not be needed
    force_register: yes
  when: sub_status.rc == 1

- name: Add Appropriate Repos (Disable)
  command: subscription-manager repos --disable="*"

- name: Add Appropriate Repos (Enable Appropriate)
  command: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable={{ ocp_repos }} --enable="rhel-7-fast-datapath-rpms"  --enable="rhel-7-server-ansible-2.6-rpms"

